### REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "andi",
  "email": "andi@gmail.com",
  "password": "password"
}

### LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "newpassword"
}

### UPDATE
PATCH http://localhost:3000/api/auth/update/674748ea95426e502facdfa4
Content-Type: application/json

{
  "name": "user update",
  "password": "newpassword"
}

